Pass through authorization header
swimos/ratchet pull request #15
Opened 2024-05-07 01:06 UTC by michael-hibachi-xyz

Address issue #14 by supporting passing through an optional authorization header from the base request object.

I tried to stick with the most minimal implementation as to stay un-opinionated about how this repo should be laid out.

2024-05-07 13:45 UTC, SirCipher requested changes

2024-05-07 13:45 UTC, SirCipher commented on ratchet_core/src/handshake/client/encoding.rs
> +    if let Some((name, value)) = &ext {
```suggestion
    if let Some((name, value)) = &auth {
```

2024-05-07 13:47 UTC, SirCipher commented
@michael-hibachi-xyz, thank you for raising an issue and submitting a fix for this. The issue that you've had has highlighted that the encoder implementation is stripping user-defined headers. Lets get this through and then I'll circle back to fix the underlying issue.

2024-05-07 16:54 UTC, michael-hibachi-xyz commented
Thanks for the quick response. Apologies for the typo, fixed the issue now.

2024-05-08 17:22 UTC, michael-hibachi-xyz commented
@SirCipher happy to change anything else, if needed :)

2024-05-09 14:52 UTC, merged

2024-05-09 15:03 UTC, SirCipher commented
@michael-hibachi-xyz released in https://github.com/swimos/ratchet/releases/tag/v0.4.2